In [ ]:
# pip install google-cloud-bigquery
# pip install db-dtypes

In [1]:
import glob
from google.cloud import bigquery
from google.oauth2 import service_account

In [2]:
key_path = glob.glob("../../core/config/*.json")[0]

In [3]:
# GCP 인증정보 객체
credentials = service_account.Credentials.from_service_account_file(key_path)

# 빅쿼리 클라이언트 객체
bigquery_client = bigquery.Client(credentials = credentials)

In [4]:
sql = f"""
SELECT *
FROM `credible-runner-405908.kb_real_estate.kb_table1`
"""
query_job = bigquery_client.query(sql).to_dataframe()

In [7]:
query_job

,date,sidoName,sigunName,guName,sigunguName,sidoCode,sigunguCode,houseDealTotal,houseDealApt,houseDealDandok,houseDealYeonrip,houseJeonseTotalIndex,houseJeonseApt,houseJeonseDandok,houseJeonseYeonrip
0,1986-01,전국,None,None,None,NaN,NaN,27.682150,15.910037,56.672388,37.418669,15.133296,9.009376,33.498810,16.090665
1,1986-01,6개광역시,None,None,None,NaN,NaN,28.604086,15.924712,57.704710,38.724357,16.601199,10.871663,32.755739,17.815171
2,1986-01,수도권,None,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1986-01,5개광역시(인천外),None,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1986-01,경기도,None,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
84439,2023-06,서울특별시,강북14개구,None,None,11.0,NaN,94.440109,89.271378,99.989435,101.034491,92.332805,85.819149,99.862843,100.304451
84440,2023-07,서울특별시,강북14개구,None,None,11.0,NaN,94.174590,88.806027,99.987835,101.024478,91.989594,85.239981,99.853126,100.262634
84441,2023-08,서울특별시,강북14개구,None,None,11.0,NaN,94.000805,88.503273,99.986231,101.006045,91.859208,85.006666,99.843136,100.262634
84442,2023-09,서울특별시,강북14개구,None,None,11.0,NaN,94.030952,88.564576,99.948927,101.005771,91.938435,85.138831,99.741996,100.314913
84443,2023-10,서울특별시,강북14개구,None,None,11.0,NaN,94.078454,88.646116,99.955611,101.005771,92.150035,85.487651,99.750605,100.352183